name: Pull request test
on: [pull_request]
jobs:
  cypress-run:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'RFR')
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm dependenicies
        run: npm install .
      # - name: jq 
      #   uses: r26d/jq-action@master
      - name: Collect files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Cypress run test
        run: |
        test_files=`python -c 'import os; print(",".join([i for i in ${{steps.files.outputs.all}} if ".test.ts" in i]))'`
        echo $test_files