name: Pull request test
on: [pull_request]
jobs:
  cypress-run:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'RFR')
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Install npm dependenicies
      #   run: npm install .
      # - name: jq 
      #   uses: r26d/jq-action@master
      - name: Collect files
        uses: trilom/file-changes-action@v1.2.3
      - name: Cypress run test
        uses: actions/setup-python@v2
      - name: kashis
        run: echo 'action_state="$HOME/files.json"' >> $GITHUB_ENV
      
      - name: pyto  
        run: |
          npx cypress run --spec `python -c 'import os; print(",".join([i for i in ${{env.action_state}} if ".test.ts" in i]))'`
