name: Pull request test
on: [pull_request]
jobs:
  cypress-run:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'RFR')
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Install npm dependenicies
      #   run: npm install .
      # - name: jq 
      #   uses: r26d/jq-action@master
      - name: Collect files
        uses: trilom/file-changes-action@v1.2.3
      - name: Cypress run test
        uses: actions/setup-python@v2
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          MY_ENV_VAR: $HOME/files.json
      - name: Printenv
      run: |
        echo "MY_ENV_VAR=${MY_ENV_VAR}"
        printenv
      - name: kashis 
        run: 
          npx cypress run --spec ${MY_ENV_VAR}
