name: Pull request test
on: [pull_request]
jobs:
  cypress-run:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'RFR')
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm dependenicies
        run: npm install .
      # - name: jq 
      #   uses: r26d/jq-action@master
      - name: Collect files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Cypress run test
        uses: actions/setup-python@v2
      - name: kashis
        run:  echo 'action_state=[".github/workflows/pr.yml","cypress/integration/tests/x.test.ts","cypress/integration/tests/y.test.ts"]' >> $GITHUB_ENV
      - name: pyto  
        run: x=`python -c 'import os; print(",".join([i for i in ${{env.action_state}} if ".test.ts" in i]))'`