name: Pull request test
on: [pull_request]
jobs:
  cypress-run:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'RFR')
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Install npm dependenicies
      #   run: npm install .

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3

      - id: event
        run: |
          test_files=`python -c 'print(",".join([i for i in ${{steps.file_changes.outputs.files_added}} if ".test.ts" in i]))'`
          echo "::set-output name=tests::$test_files"
      - name: output
        run: ${{ steps.event.outputs.tests }}